export const TEST_IDS = {
  DASHBOARD_RESET_BUTTON:   'dashboard-reset-button',
  DASHBOARD_MONTH_PREV:     'dashboard-month-prev',
  DASHBOARD_MONTH_NEXT:     'dashboard-month-next',
  DASHBOARD_TRANSACTIONS_LIST: 'dashboard-transactions-list',
  DASHBOARD_TRANSACTION_ITEM:  'dashboard-transaction-item',
  DASHBOARD_SEARCH_INPUT:   'dashboard-search-input',
  DASHBOARD_FILTER_TODOS:   'dashboard-filter-todos',
  DASHBOARD_FILTER_RAPPICARD: 'dashboard-filter-rappicard',
  DASHBOARD_FILTER_RAPPIPAY:  'dashboard-filter-rappipay',
  DASHBOARD_DONUT_CHART:    'dashboard-donut-chart',
  DASHBOARD_DONUT_SLICE:    'dashboard-donut-slice',
  ADVISOR_PANEL:            'advisor-panel',
  ADVISOR_REFRESH_BUTTON:   'advisor-refresh-button',
  ADVISOR_INSIGHT_CARD:     'advisor-insight-card',
  ADVISOR_CHAT_TOGGLE:      'advisor-chat-toggle',
  ADVISOR_CHAT_INPUT:       'advisor-chat-input',
  ADVISOR_CHAT_SEND:        'advisor-chat-send',
  ADVISOR_CHAT_MESSAGE:     'advisor-chat-message',
  BUDGET_MANAGER:           'budget-manager',
  BUDGET_CATEGORY_INPUT:    'budget-category-input',
  BUDGET_SAVE_BUTTON:       'budget-save-button',
  ONBOARDING_STEP1_CTA:     'onboarding-step1-cta',
  FORWARDING_WIZARD_DONE_CONTINUE: 'forwarding-wizard-done-continue',
  FORWARDING_WIZARD_FILTER_DONE:   'forwarding-wizard-filter-done',
  ONBOARDING_STEP3_CONTINUE:'onboarding-step3-continue',
  AUTH_GOOGLE_BUTTON:       'auth-google-button',
  AUTH_LOGOUT_BUTTON:       'auth-logout-button',
  DASHBOARD_MONTH_PROGRESS: 'dashboard-month-progress',
  DASHBOARD_HELP_BUTTON:    'dashboard-help-button',
  DASHBOARD_FORWARDING_BUTTON: 'dashboard-forwarding-button',
} as const
