export const TEST_IDS = {
  DASHBOARD_SYNC_BUTTON:    'dashboard-sync-button',
  DASHBOARD_RESET_BUTTON:   'dashboard-reset-button',
  DASHBOARD_MONTH_PREV:     'dashboard-month-prev',
  DASHBOARD_MONTH_NEXT:     'dashboard-month-next',
  DASHBOARD_BALANCE_AMOUNT: 'dashboard-stats-balance-amount',
  DASHBOARD_GASTOS_AMOUNT:  'dashboard-stats-gastos-amount',
  DASHBOARD_INGRESOS_AMOUNT:'dashboard-stats-ingresos-amount',
  DASHBOARD_TRANSACTIONS_LIST: 'dashboard-transactions-list',
  DASHBOARD_TRANSACTION_ITEM:  'dashboard-transaction-item',
  DASHBOARD_SEARCH_INPUT:   'dashboard-search-input',
  DASHBOARD_FILTER_TODOS:   'dashboard-filter-todos',
  DASHBOARD_FILTER_RAPPICARD: 'dashboard-filter-rappicard',
  DASHBOARD_FILTER_RAPPIPAY:  'dashboard-filter-rappipay',
  DASHBOARD_DONUT_CHART:    'dashboard-donut-chart',
  DASHBOARD_DONUT_SLICE:    'dashboard-donut-slice',
  ADVISOR_PANEL:            'advisor-panel',
  ADVISOR_REFRESH_BUTTON:   'advisor-refresh-button',
  ADVISOR_INSIGHT_CARD:     'advisor-insight-card',
  ADVISOR_CHAT_TOGGLE:      'advisor-chat-toggle',
  ADVISOR_CHAT_INPUT:       'advisor-chat-input',
  ADVISOR_CHAT_SEND:        'advisor-chat-send',
  ADVISOR_CHAT_MESSAGE:     'advisor-chat-message',
  BUDGET_MANAGER:           'budget-manager',
  BUDGET_CATEGORY_INPUT:    'budget-category-input',
  BUDGET_SAVE_BUTTON:       'budget-save-button',
  ONBOARDING_STEP1_CTA:     'onboarding-step1-cta',
  ONBOARDING_STEP2_SYNC:    'onboarding-step2-sync',
  ONBOARDING_STEP2_STATUS:  'onboarding-step2-status',
  ONBOARDING_STEP3_CONTINUE:'onboarding-step3-continue',
  AUTH_GOOGLE_BUTTON:       'auth-google-button',
  AUTH_LOGOUT_BUTTON:       'auth-logout-button',
} as const
